name: Deploy site to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clone repo
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          sudo apt install brotli
          pnpm install
      - name: Update sites
        run: 'cd listing && git pull'
      - name: Update RSS
        run: |
          pnpm rss:fetch
          brotli pages/public/feed.json
          rm pages/public/feed.json
      - name: Build with VitePress
        run: pnpm docs:build
      - uses: cloudflare/wrangler-action@v3
        name: Deploy pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
